# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 08:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_url', models.CharField(max_length=255, unique=True)),
                ('target_url', models.CharField(max_length=1000)),
                ('redirects', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TargetDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=1000)),
                ('device_type', models.PositiveSmallIntegerField(choices=[(1, 'Mobile'), (2, 'Tablet')], db_index=True)),
                ('short_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_devices', to='api.ShortURL')),
            ],
        ),
    ]
